name: kanzoo
description: "Aplikasi pembelajaran bahasa Arab untuk siswa MTs. Menggantikan LKS tradisional dengan materi digital dan latihan soal interaktif."
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/materials/qiroah/
    - assets/materials/istima/audio/bab 1/
    - assets/materials/istima/audio/bab 2/
    - assets/materials/istima/audio/bab 3/

  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-Regular.ttf
          weight: 400
        - asset: assets/fonts/Signika-Light.ttf
          weight: 300
        - asset: assets/fonts/Signika-Bold.ttf
          weight: 700
    - family: Noto Naskh Arabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
          weight: 400
